# Generated by Django 5.0 on 2023-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpage',
            name='documents',
            field=models.ManyToManyField(blank=True, to='wagtaildocs.document'),
        ),
    ]
