# Generated by Django 5.0 on 2023-12-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_topicpage_documents'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicIndex',
            new_name='TopicIndexPage',
        ),
    ]
